FROM alpine:3.4
MAINTAINER smallweirdnum@gmail.com

ENV PANDAS_VERSION <%= pandas %>
RUN apk add --no-cache python3-dev && \
    apk add --no-cache --virtual .build-deps g++ && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip3 install numpy==1.11.1 && \
    pip3 install pandas==$PANDAS_VERSION && \
    apk del .build-deps
