FROM alpine:3.6
ARG PANDAS_VERSION
ENV PANDAS_VERSION ${PANDAS_VERSION:-0.20.2}
RUN apk add --no-cache python-dev py-pip && \
    apk add --no-cache --virtual .build-deps g++ && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip install numpy==1.13.0 && \
    pip install pandas==$PANDAS_VERSION && \
    apk del .build-deps
