FROM alpine:3.6
ARG PANDAS_VERSION=0.20.3
RUN apk add --no-cache python3-dev && \
    apk add --no-cache --virtual .build-deps g++ && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip3 install numpy==1.13.1 && \
    pip3 install pandas==${PANDAS_VERSION} && \
    apk del .build-deps
