name: Docker Build
description: Build Docker image
inputs:
  file:
    description: Dockerfile
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
    - run: npm install -g dockerlint
      shell: bash
    - run: dockerlint -f ${{ inputs.file }}
      shell: bash
