FROM python:3.6-alpine
ARG PANDAS_VERSION
ENV PANDAS_VERSION ${PANDAS_VERSION:-0.20.2}
RUN apk add --no-cache g++ && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip3 install pandas==${PANDAS_VERSION}
