name: push
on:
  push:
    tags:
      - "*"
jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - Dockerfile
          - Dockerfile.alpine
          - Dockerfile.jupyter
          - Dockerfile.slim
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: lint ${{ matrix.file }}
        uses: ./.github/actions/lint
        with:
          file: ${{ matrix.file }}
      - name: build ${{ matrix.file }}
        uses: ./.github/actions/build
        with:
          file: ${{ matrix.file }}
          platform: ${{ matrix.platform }}
      - run: make push
