name: push
on:
  push:
    tags:
      - "*"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g dockerlint
      - run: dockerlint
  build-push:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        target:
          - alpine
          - jupyter
          - latest
          - slim
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make ${{ matrix.target }}
      - run: make push
